version: '3.8'
services:
  gateway:
    build:
    image:
    container_name:
    ports:
      - "8080:8080"
    depends_on:
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build:
    image:
    container_name:
    ports:
      - "9090:9090"
    depends_on:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  db:
    image: postgres:13.7-alpine
    container_name: data_base
    ports:
      - "6541:5432"
    environment:
      - DB_NAME=shareit
      - POSTGRES_USER=andersen
      - POSTGRES_PASSWORD=andersen
      - DB_HOST=db
      - DB_PORT=5432